---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-ast
          - id: check-added-large-files
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11 # or specific tag
      hooks:
          - id: yamlfmt

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort

    - repo: local
      hooks:
          - id: unittest
            name: Run Python unittests
            language: python
            entry: pytest #--doctest-modules
            pass_filenames: false
