preprocess:
    train:
        resize: 512
    val:
        resize: 256
batch_transform:
    train:
        random_resize_crop: 224
    val:
        center_crop: 224
normalize:
   - [0.485, 0.456, 0.406]
   - [0.229, 0.224, 0.225]