# @package model_cfg

defaults:
    # - class-balanced-ce-loss
    - ce-loss

# loss:
#     _target_: torch.nn.CrossEntropyLoss
    # Note: label_smoothing isnt an option in CELoss until some time after pytorch version 1.8.1
    # label_smoothing: 0.0