# @package train

## conf/train/pl_trainer/base.yaml


defaults:
    - _self_
    - strategy: default



# pl_trainer:
_target_: pytorch_lightning.Trainer
fast_dev_run: False # Enable this for debug purposes
accelerator: "gpu"
devices: 1
precision: 16
enable_model_summary: true
log_every_n_steps: 5
max_epochs: ${hp.max_epochs}
accumulate_grad_batches: 1

